fixed CD

diff --git a/.github/workflows/reusable-deploy.yml b/.github/workflows/reusable-deploy.yml
--- a/.github/workflows/reusable-deploy.yml
+++ b/.github/workflows/reusable-deploy.yml
@@ -94,16 +94,16 @@ jobs:
         run: |
           kubectl apply -f ${{ inputs.deployment-file }}
 
-      - name: Configurar Git para Commits Automáticos
-        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci auto-fix]')
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
+      # - name: Configurar Git para Commits Automáticos
+      #   if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci auto-fix]')
+      #   run: |
+      #     git config user.name "github-actions[bot]"
+      #     git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Commit y Push de Cambios Automatizados
-        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci auto-fix]')
-        run: |
-          git add ${{ inputs.deployment-file }}
-          git commit -m "Auto-fix: Actualizar imagen de Docker para ${{ inputs.service-name }} [ci auto-fix]"
-          git pull --rebase origin main || { echo "Error al hacer pull"; exit 1; }
-          git push
+      # - name: Commit y Push de Cambios Automatizados
+      #   if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci auto-fix]')
+      #   run: |
+      #     git add ${{ inputs.deployment-file }}
+      #     git commit -m "Auto-fix: Actualizar imagen de Docker para ${{ inputs.service-name }} [ci auto-fix]"
+      #     git pull --rebase origin main || { echo "Error al hacer pull"; exit 1; }
+      #     git push
